/*
 * Task 2
 */
 
-- Question 2.1

/*
-- Need to disable the constraint
DELETE FROM ACADEMIC WHERE ACADEMIC.STAFF# NOT IN (
  SELECT DISTINCT TEACHES.LECTURER FROM TEACHES
    WHERE TEACHES.YEAR > TO_CHAR(ADD_MONTHS(SYSDATE, -12 * 3), 'YYYY')
  );
*/

-- Question 2.2

/*
CREATE TABLE CSCI235 (
  staff# NUMBER(10)	NOT NULL,
  first_name VARCHAR(30)	NOT NULL,
  last_name VARCHAR(30)	NOT NULL,
  email VARCHAR(50)	NOT NULL,
  bldg# NUMBER(5)	NOT NULL,
  room# VARCHAR(5)	NOT NULL,
  phone# NUMBER(4)	NOT NULL,
  position VARCHAR(20)	NOT NULL,
  
	CONSTRAINT CSCI235_pkey PRIMARY KEY(staff#),
	CONSTRAINT CSCI235_ckey1 UNIQUE (first_name, last_name),
	CONSTRAINT CSCI235_ckey2 UNIQUE(email),
	CONSTRAINT CSCI235_ckey3 UNIQUE(bldg#, room#),
	CONSTRAINT CSCI235_ckey4 UNIQUE(phone#),
	CONSTRAINT CSCI235_fkey4 FOREIGN KEY (position)
				REFERENCES LPosition(position));
        
INSERT INTO CSCI235 (STAFF#, FIRST_NAME, LAST_NAME, EMAIL, BLDG#, ROOM#, PHONE#, POSITION)
  SELECT DISTINCT STAFF#, FIRST_NAME, LAST_NAME, EMAIL, BLDG#, ROOM#, PHONE#, POSITION FROM ACADEMIC
    JOIN TEACHES ON TEACHES.LECTURER = ACADEMIC.STAFF#
    WHERE TEACHES.CODE = 'CSCI235';

ALTER TABLE TEACHES ADD CONSTRAINT Teaches_FKEY2 FOREIGN KEY (LECTURER)
				REFERENCES CSCI235(STAFF#);

-- DROP TABLE CSCI235 PURGE;

*/

-- Question 2.3

/*
ALTER TABLE ACADEMIC ADD TOTAL_SUBJECTS NUMBER(10);

UPDATE ACADEMIC A1 SET TOTAL_SUBJECTS = (SELECT COUNT(TEACHES.CODE) FROM TEACHES WHERE TEACHES.LECTURER = A1.STAFF#);
*/
