SET ECHO ON;
SPOOL task1.lst;

SET LINESIZE 300;

/*
 * Task 1
 */
 
-- Question 1.1

CREATE OR REPLACE VIEW VIEW_1_1 AS
SELECT DISTINCT ACADEMIC.FIRST_NAME, ACADEMIC.LAST_NAME, SUBJECT.CODE, SUBJECT.NAME FROM ACADEMIC
  JOIN TEACHES ON ACADEMIC.STAFF# = TEACHES.LECTURER
  JOIN RUNNINGSUBJECT ON TEACHES.CODE = RUNNINGSUBJECT.CODE AND TEACHES.ASESSION = RUNNINGSUBJECT.ASESSION AND TEACHES.YEAR = RUNNINGSUBJECT.YEAR
  JOIN SUBJECT ON RUNNINGSUBJECT.CODE = SUBJECT.CODE
  WHERE SUBJECT.CREDITS = 12 AND RUNNINGSUBJECT.ENROLMENT > 50;
  
SELECT * FROM VIEW_1_1;

-- Question 1.2

CREATE OR REPLACE VIEW VIEW_1_2 AS
SELECT DISTINCT SUBJECT.CODE, SUBJECT.NAME, COUNT(TEACHES.LECTURER) AS "Total Lecturers" FROM SUBJECT
  JOIN RUNNINGSUBJECT ON SUBJECT.CODE = RUNNINGSUBJECT.CODE
  JOIN TEACHES ON RUNNINGSUBJECT.CODE = TEACHES.CODE  AND TEACHES.ASESSION = RUNNINGSUBJECT.ASESSION AND TEACHES.YEAR = RUNNINGSUBJECT.YEAR
  JOIN ACADEMIC ON TEACHES.LECTURER = ACADEMIC.STAFF#
  WHERE TEACHES.YEAR < 2016 AND RUNNINGSUBJECT.CODE IN (
    'CSCI222',
    'CSCI212',
    'CSCI235'
  ) GROUP BY SUBJECT.CODE, SUBJECT.NAME;
  
SELECT * FROM VIEW_1_2;
  
-- Question 1.3

CREATE OR REPLACE VIEW VIEW_1_3 AS
SELECT ACADEMIC.STAFF#, ACADEMIC.FIRST_NAME, ACADEMIC.LAST_NAME FROM TEACHES
  JOIN ACADEMIC ON ACADEMIC.STAFF# = TEACHES.LECTURER
  JOIN RUNNINGSUBJECT ON RUNNINGSUBJECT.CODE = TEACHES.CODE AND TEACHES.ASESSION = RUNNINGSUBJECT.ASESSION AND TEACHES.YEAR = RUNNINGSUBJECT.YEAR
  WHERE TEACHES.YEAR = to_char(SYSDATE, 'YYYY') AND TEACHES.ASESSION != 'AUTUMN';
  
SELECT * FROM VIEW_1_3;

-- Question 1.4

CREATE OR REPLACE VIEW VIEW_1_4 AS
SELECT ACADEMIC.STAFF#, ACADEMIC.FIRST_NAME, ACADEMIC.LAST_NAME FROM ACADEMIC
  JOIN TEACHES ON ACADEMIC.STAFF# = TEACHES.LECTURER
  WHERE TEACHES.CODE = 'CSCI235'
    INTERSECT
SELECT ACADEMIC.STAFF#, ACADEMIC.FIRST_NAME, ACADEMIC.LAST_NAME FROM ACADEMIC
  JOIN TEACHES ON ACADEMIC.STAFF# = TEACHES.LECTURER
  WHERE TEACHES.CODE = 'CSCI204'
    INTERSECT
SELECT ACADEMIC.STAFF#, ACADEMIC.FIRST_NAME, ACADEMIC.LAST_NAME FROM ACADEMIC
  JOIN TEACHES ON ACADEMIC.STAFF# = TEACHES.LECTURER
  WHERE TEACHES.CODE = 'CSCI222';

SELECT * FROM VIEW_1_4;

SPOOL OFF;
