/*
 * Task 3
 */
 
/*
CREATE USER SCOTT IDENTIFIED BY PASSWORD;
*/
 
-- Question 3.1 
 
/*
GRANT SELECT, INSERT, UPDATE ON TEACHES TO SCOTT;
*/
 
-- Question 3.2

/*
GRANT CREATE TABLE TO SCOTT;
GRANT REFERENCES (CODE) ON RUNNINGSUBJECT TO SCOTT;
*/

-- Question 3.3

CREATE OR REPLACE VIEW VIEW_3_3 AS
  SELECT DISTINCT * FROM ACADEMIC
    JOIN TEACHES ON TEACHES.LECTURER = ACADEMIC.STAFF#
    WHERE TEACHES.CODE IN (
      'CSCI235',
      'CSCI204',
      'CSCI124'
    );
    
GRANT SELECT ON VIEW_3_3 TO SCOTT;

      
  