SET ECHO ON;
SPOOL task4.lst;

-- Question 1
SELECT PTITLE FROM POSITION P WHERE EXISTS (
  SELECT APPLIES.P# FROM APPLIES WHERE APPLIES.P# = P.P#
);

-- Question 2
SELECT FNAME, LNAME FROM APPLICANT APP WHERE EXISTS (
  SELECT APPLIES.P# FROM APPLIES WHERE APPLIES.A# = APP.A#
);

-- Question 3
SELECT CTITLE FROM COURSEPASSED WHERE EXISTS (
  SELECT A# FROM APPLICANT WHERE EXISTS (
    SELECT A# FROM APPLIES WHERE EXISTS (
      SELECT P# FROM POSITION WHERE EXISTS (
        SELECT P# FROM SNEEDED WHERE (
          COURSEPASSED.A# = APPLICANT.A#
          AND
          APPLICANT.A# = APPLIES.A#
          AND
          APPLIES.P# = POSITION.P#
          AND
          POSITION.P# = SNEEDED.P# 
          AND
          SNEEDED.SNAME = 'C PROGRAMMING'
        )
      )
    )
  )
);

SPOOL OFF;
