SET ECHO ON;
SPOOL task2.lst;

-- Question 1
SELECT APPLICANT.FNAME || ' ' || APPLICANT.LNAME AS "Full Name", SPOSSESSED.SNAME FROM APPLICANT LEFT OUTER JOIN SPOSSESSED ON APPLICANT.A# = SPOSSESSED.A#;

-- Question 2
SELECT S.SKILL, P.PTITLE FROM LSKILL S
LEFT JOIN SNEEDED SN ON S.SKILL = SN.SNAME
LEFT JOIN POSITION P ON P.P# = SN.P#;

-- Question 3
SELECT APPLICANT.FNAME, COUNT(SPOSSESSED.SNAME) FROM APPLICANT LEFT OUTER JOIN SPOSSESSED ON
APPLICANT.A# = SPOSSESSED.A# GROUP BY APPLICANT.FNAME;

SPOOL OFF;
