SET ECHO ON;
SPOOL task2.lst;

SET LINESIZE 		1000
SET PAGESIZE 		1000

-- Question 1
SELECT FNAME || ' ' || LNAME AS "FULL NAME" FROM APPLICANT WHERE APPLICANT.A# = ANY
  (SELECT A# FROM APPLIES A1 WHERE A1.APPDATE < ALL 
    (SELECT APPDATE FROM APPLIES A2 WHERE A2.A# = 1
  )
);

-- Question 2
SELECT PTITLE FROM POSITION WHERE SALARY >= ALL (
  SELECT SALARY FROM POSITION
);

-- Question 3
SELECT FNAME || ' ' || LNAME AS "FULL NAME", MAX(APPDATE) FROM APPLICANT JOIN APPLIES ON APPLICANT.A# = APPLIES.A#
GROUP BY FNAME || ' ' || LNAME HAVING MAX(APPDATE) < ALL (SELECT APPDATE FROM APPLIES WHERE A# = 7);

SPOOL OFF;
