SET ECHO ON;
SPOOL task1.lst;

SET LINESIZE 		1000
SET PAGESIZE 		1000

-- Question 1
SELECT PTITLE FROM POSITION WHERE NOT EXISTS (
  SELECT APPLIES.P# FROM APPLIES WHERE POSITION.P# = APPLIES.P#
);

-- Question 2
-- Applicant and Applies
SELECT FNAME || LNAME AS "FULL NAME" FROM APPLICANT WHERE NOT EXISTS (
  SELECT APPLIES.A# FROM APPLIES WHERE APPLICANT.A# = APPLIES.A#
);

-- Question 3
SELECT PTITLE FROM POSITION P1 WHERE NOT EXISTS (
  SELECT SALARY FROM POSITION P2 WHERE P2.SALARY > P1.SALARY
);

SPOOL OFF;
