SET ECHO ON;
SPOOL task4.lst;

SET LINESIZE 		1000
SET PAGESIZE 		1000

-- Question 1 - CHECK THIS
CREATE OR REPLACE VIEW VAPPS (P#, TOTAP) AS (
  SELECT POSITION.P#, COUNT(APPLIES.A#) FROM POSITION JOIN APPLIES ON POSITION.P# = APPLIES.A# GROUP BY POSITION.P#
);

SELECT PTITLE, SALARY FROM POSITION JOIN VAPPS ON POSITION.P# = VAPPS.P# WHERE VAPPS.TOTAP >= 1;

-- Question 2
CREATE OR REPLACE VIEW MORE_THAN_ONE_APP AS (
  SELECT * FROM APPLICANT A1 WHERE
    (SELECT COUNT(*) FROM APPLIES A2 WHERE A1.A# = A2.A# GROUP BY A2.A#) > 1
);

GRANT SELECT ON MORE_THAN_ONE_APP TO SCOTT;

-- Question 3
GRANT REFERENCES (A#) ON APPLIES TO SCOTT;

SPOOL OFF;
