SET ECHO ON
SET HEADING OFF
SET FEEDBACK OFF

CREATE TABLE CAR(
  REGO CHAR(8) NOT NULL,
  MAKE VARCHAR(20) NOT NULL,
  CONSTRAINT CAR_PKEY PRIMARY KEY(REGO)
);

INSERT INTO CAR VALUES('PKR856UK', 'TOYOTA');
INSERT INTO CAR VALUES('AL0877UK', 'TOYOTA');

COMMIT;

SELECT REGO, MAKE, TO_CHAR(SYSDATE, 'DD/MM/YY') NOW FROM CAR;
DROP TABLE CAR PURGE
