SET ECHO ON;
SPOOL task2-2.lst;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET SERVEROUTPUT ON;

BEGIN

  UPDATE POSITION SET POSITION.EXTRAS = POSITION.EXTRAS || ', computer'
    WHERE POSITION.EXTRAS LIKE '%mouse pad%';

  UPDATE POSITION SET POSITION.EXTRAS = POSITION.EXTRAS || ', Rolls Royce'
    WHERE POSITION.ENAME = 'University of New South Wales';
    
  COMMIT;

END;
/

SELECT * FROM POSITION;

SPOOL OFF;
