SET ECHO ON;
SPOOL task1.lst;

CREATE DATABASE LINK "DB.DATA-PC07" CONNECT TO jm617 IDENTIFIED BY Bh43B4 USING 'data-pc07';

CREATE TABLE EMPLOYEE AS (SELECT * FROM EMPLOYEE@"DB.DATA-PC07");
CREATE TABLE DRIVER AS (SELECT * FROM DRIVER@"DB.DATA-PC07");
CREATE TABLE ADMIN AS (SELECT * FROM ADMIN@"DB.DATA-PC07");
CREATE TABLE TRUCK AS (SELECT * FROM TRUCK@"DB.DATA-PC07");
CREATE TABLE TRIP AS (SELECT * FROM TRIP@"DB.DATA-PC07");
CREATE TABLE TRIPLEG AS (SELECT * FROM TRIPLEG@"DB.DATA-PC07");
CREATE TABLE SKILL AS (SELECT * FROM SKILL@"DB.DATA-PC07");
CREATE TABLE SKILLREQUIRED AS (SELECT * FROM SKILLREQUIRED@"DB.DATA-PC07");
CREATE TABLE SKILLPOSSESSED AS (SELECT * FROM SKILLPOSSESSED@"DB.DATA-PC07");

DELETE FROM ADMIN WHERE E# IN (SELECT E# FROM EMPLOYEE WHERE STATE NOT IN ('WA', 'Vic', 'Tas'));
DELETE FROM DRIVER WHERE E# IN (SELECT E# FROM EMPLOYEE WHERE STATE NOT IN ('WA', 'Vic', 'Tas'));
DELETE FROM EMPLOYEE WHERE STATE NOT IN ('WA', 'Vic', 'Tas');

SPOOL OFF;
