SET ECHO ON;
SPOOL task2.lst;

-- Question 1
SELECT DNAME FROM DEPTLOC WHERE CITY IN ('BOSTON', 'DALLAS')
MINUS (
SELECT DNAME FROM DEPTLOC WHERE CITY = 'DALLAS'
INTERSECT
SELECT DNAME FROM DEPTLOC WHERE CITY = 'BOSTON'
);

-- Question 2
SELECT DNAME FROM DEPARTMENT
MINUS
SELECT DNAME FROM EMPLOYEE;

-- Question 3
SELECT CITY FROM DEPTLOC WHERE DNAME = 'SALES'
MINUS
SELECT CITY FROM DEPTLOC WHERE DNAME = 'TRANSPORT';

-- Question 4
SELECT DISTINCT DNAME
FROM DEPTLOC DL
WHERE DL.DNAME IN ('SALES', 'TRANSPORT', 'RESEARCH')
AND NOT EXISTS (
SELECT CITY FROM DEPTLOC
MINUS
SELECT CITY FROM DEPTLOC
WHERE DNAME = DL.DNAME
);

SPOOL OFF;