SET ECHO ON;
SPOOL task1.lst;

-- Question 1
SELECT DISTINCT CITY FROM DEPTLOC;

-- Question 2
SELECT DNAME, BUDGET FROM DEPARTMENT ORDER BY BUDGET ASC;

-- Question 3
SELECT ENAME, HIREDATE FROM EMPLOYEE WHERE HIREDATE BETWEEN '01/JAN/1980' AND '31/DEC/1990';

SPOOL OFF;