SET ECHO ON;
SPOOL task4.lst;

-- Question 1
SELECT DEPARTMENT.DNAME, DEPARTMENT.BUDGET, DEPTLOC.CITY, DEPTLOC.STREET#, DEPTLOC.BLDG#, DEPTLOC.LEVEL#
FROM DEPTLOC JOIN DEPARTMENT ON DEPARTMENT.DNAME = DEPTLOC.DNAME;

-- Question 2
SELECT DEPARTMENT.DNAME, PROJECT.TITLE
FROM DEPARTMENT JOIN DP ON DEPARTMENT.DNAME = DP.DNAME
JOIN PROJECT ON DP.P# = PROJECT.P#;

-- Question 3
SELECT DEPARTMENT.DNAME, DEPARTMENT.BUDGET, DEPARTMENT.CHAIRMAN, PROJECT.TITLE, PROJECT.BUDGET, PROJECT.STARTD, PROJECT.ENDD
FROM DEPARTMENT JOIN DP ON DEPARTMENT.DNAME = DP.DNAME JOIN PROJECT ON DP.P# = PROJECT.P#;

SPOOL OFF;
